# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BawangcanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_time', models.CharField(max_length=255)),
                ('activity_type', models.IntegerField()),
                ('activity_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BawangcanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_activity_id', models.CharField(max_length=255)),
                ('record_create_time', models.IntegerField()),
                ('record_user_id', models.CharField(max_length=255)),
                ('record_record_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BawangcanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_activity_id', models.CharField(max_length=255)),
                ('status_start_time', models.IntegerField(max_length=255)),
                ('status_end_time', models.IntegerField(max_length=255)),
                ('status_count', models.IntegerField()),
                ('status_status', models.IntegerField()),
                ('status_record_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('user_money', models.IntegerField()),
            ],
        ),
    ]
