# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawangcan', '0003_bawangcanaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bawangcanrecord',
            name='record_record_id',
        ),
        migrations.RemoveField(
            model_name='bawangcanstatus',
            name='status_record_id',
        ),
        migrations.AddField(
            model_name='bawangcanstatus',
            name='status_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bawangcanstatus',
            name='status_end_time',
            field=models.IntegerField(null=True),
        ),
    ]
