# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bawangcan', '0005_auto_20170113_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bawangcanstatus',
            name='status_type',
        ),
    ]
